/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservationdbms;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.* ;
import java.text.SimpleDateFormat;
import java.util.Currency;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class First_page extends javax.swing.JFrame  {
    static Connection conn = null ;
    static Statement stmt = null;
    static ResultSet rs = null ;
    static ResultSetMetaData metadata = null ;
    PreparedStatement pstmt  ;
    LoginFrame login = new LoginFrame() ;
    PaymentProcess paymentProcess = new PaymentProcess() ;
    JLabel lbl ;
    static String From ;
    static String To ;
    static String Fname ;
    static String Fno ;
    static String Dept ;
    static String Date ;
    static String Time ;
    static int CostPerSeat ;
    static String RE;
    static int res1 ;
    static int res2 ;
    static int res3 ;
    static int totalAmount ;
    static JFrame frameFP ;
    LoginFrame lf ;
    

    static{ 
        try {
            RE = "\u20B9";
    byte[] utf8 = RE.getBytes("UTF-8");

    RE = new String(utf8, "UTF-8");
    System.out.println(RE);
        } catch (Exception e) {
        }
    }
     int totalPassenger;
   
    /**
     * Creates new form First_page
     */
    public First_page() {
         
        initComponents();
       // new SeatingArrangement(this) ;
        frameFP = this ;
      frameFP.setVisible(true);
    //    System.out.println(this.getClass());
      
      //  lbl = JLabel();
      this.setLocationRelativeTo(null);
      loginButton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                           System.out.println("HIE LOGIN BUTTON IS CLICKED");
                           lf = new LoginFrame() ;
                           lf.setFirst_pageFrame(First_page.this);
                           lf.setVisible(true);
                           
                           
                   

            }
       //    static {
       //     System.out.println("IM OUT OF LOGIN");
              
            
            
      });
     
 
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BUTTONGROUP = new javax.swing.ButtonGroup();
        Second_Page_panel = new javax.swing.JPanel();
        Taxeslbl = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        childrencostlbl = new javax.swing.JLabel();
        infantcostlbl = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Adultcostlbl = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        xChildrenlbl = new javax.swing.JLabel();
        Tolbl = new javax.swing.JLabel();
        Fromlbl = new javax.swing.JLabel();
        FlightNOlbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        timelbl = new javax.swing.JLabel();
        FlightNamelbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        xAdultlbl = new javax.swing.JLabel();
        xInfantlbl = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        DepartureDatelbl = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Totalamountlbl = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        NumofAdultslbl = new javax.swing.JLabel();
        Numofchildrenlbl = new javax.swing.JLabel();
        ChildrenSpinSecondPage = new javax.swing.JSpinner();
        InfantSpinSecondPage = new javax.swing.JSpinner();
        AdultSpinSecondPage = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        infantcostlbl1 = new javax.swing.JLabel();
        AgreeAndProceedBTN = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        First_page_panel = new javax.swing.JPanel();
        fromLabel = new javax.swing.JLabel();
        fromLabel2 = new javax.swing.JLabel();
        FromComboBox = new javax.swing.JComboBox<>();
        ToComboBox = new javax.swing.JComboBox<>();
        OneWayTripRB = new javax.swing.JRadioButton();
        RoundTripRB = new javax.swing.JRadioButton();
        SearchButton = new javax.swing.JButton();
        SwapLabel = new javax.swing.JLabel();
        DateSelector = new com.toedter.calendar.JDateChooser();
        Arriveslbl = new javax.swing.JLabel();
        Departurelbl = new javax.swing.JLabel();
        DateSelector1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ChildrenSpin = new javax.swing.JSpinner();
        InfantSpin = new javax.swing.JSpinner();
        AdultSpin = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        FlightDisplayTableJScroll = new javax.swing.JScrollPane();
        FlightDisplayTable = new javax.swing.JTable();
        welcomeLbl = new javax.swing.JLabel();
        AirIndialbl = new javax.swing.JLabel();
        AirAsialbl = new javax.swing.JLabel();
        Indigolbl = new javax.swing.JLabel();
        SpiceJetlbl = new javax.swing.JLabel();
        StartAirwayslbl = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        NextBtn = new javax.swing.JButton();
        userlbl = new javax.swing.JLabel();
        BACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AIRLINE RESERVATION");
        setPreferredSize(new java.awt.Dimension(1160, 720));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Second_Page_panel.setBackground(new java.awt.Color(147, 174, 255));
        Second_Page_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Second_Page_panel.setForeground(new java.awt.Color(255, 255, 255));
        Second_Page_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Taxeslbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        Taxeslbl.setForeground(new java.awt.Color(255, 255, 255));
        Taxeslbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Taxeslbl.setText("3479");
        Second_Page_panel.add(Taxeslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, 70, 20));

        jLabel38.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("PRICE (RS)");
        Second_Page_panel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FARE : SUMMARY");
        Second_Page_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 200, 20));

        jLabel32.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("TOTAL AMOUNT");
        Second_Page_panel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 130, -1));

        childrencostlbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        childrencostlbl.setForeground(new java.awt.Color(255, 255, 255));
        Second_Page_panel.add(childrencostlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, 70, 20));

        infantcostlbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        infantcostlbl.setForeground(new java.awt.Color(255, 255, 255));
        Second_Page_panel.add(infantcostlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 70, 20));

        jLabel29.setBackground(new java.awt.Color(153, 153, 153));
        jLabel29.setOpaque(true);
        Second_Page_panel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 290, 5));

        Adultcostlbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        Adultcostlbl.setForeground(new java.awt.Color(255, 255, 255));
        Second_Page_panel.add(Adultcostlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, 70, 20));

        jLabel30.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("TAXES AND FEES :");
        Second_Page_panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 130, -1));

        jLabel25.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("BASE FARE");
        Second_Page_panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 80, -1));

        jLabel26.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("CHILDREN   x ");
        Second_Page_panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, -1, -1));

        jLabel27.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("INFANT   x ");
        Second_Page_panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 70, -1));

        xChildrenlbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        xChildrenlbl.setForeground(new java.awt.Color(255, 255, 255));
        xChildrenlbl.setText("0 ");
        Second_Page_panel.add(xChildrenlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 20, -1));

        Tolbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        Tolbl.setForeground(new java.awt.Color(255, 255, 255));
        Second_Page_panel.add(Tolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 130, 20));

        Fromlbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        Fromlbl.setForeground(new java.awt.Color(255, 255, 255));
        Second_Page_panel.add(Fromlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, 20));

        FlightNOlbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        FlightNOlbl.setForeground(new java.awt.Color(255, 255, 255));
        Second_Page_panel.add(FlightNOlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 120, 20));

        jLabel11.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TO :");
        Second_Page_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 30, 20));

        jLabel12.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("FROM :");
        Second_Page_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 50, 20));

        timelbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        Second_Page_panel.add(timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 130, 20));

        FlightNamelbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        FlightNamelbl.setForeground(new java.awt.Color(255, 255, 255));
        Second_Page_panel.add(FlightNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 140, 20));

        jLabel15.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("FNO :");
        Second_Page_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 40, 20));

        jLabel16.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("FLIGHT NAME : ");
        Second_Page_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 110, 20));

        jLabel28.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel28.setText("*INSTRUCTIONS*");
        Second_Page_panel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, 20));

        xAdultlbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        xAdultlbl.setForeground(new java.awt.Color(255, 255, 255));
        xAdultlbl.setText("0");
        Second_Page_panel.add(xAdultlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 20, -1));

        xInfantlbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        xInfantlbl.setForeground(new java.awt.Color(255, 255, 255));
        xInfantlbl.setText("0");
        Second_Page_panel.add(xInfantlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 20, -1));

        jLabel37.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("ADULT   x  ");
        Second_Page_panel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("DEPARTURE :");
        Second_Page_panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 100, 20));

        DepartureDatelbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        DepartureDatelbl.setForeground(new java.awt.Color(255, 255, 255));
        Second_Page_panel.add(DepartureDatelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 130, 20));

        jLabel19.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("TIME :");
        Second_Page_panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 50, 20));

        Totalamountlbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        Totalamountlbl.setForeground(new java.awt.Color(255, 255, 255));
        Second_Page_panel.add(Totalamountlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 290, 110, 20));

        jLabel20.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("TRAVELLERS : ");
        Second_Page_panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabel21.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("INFANT");
        Second_Page_panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        NumofAdultslbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        NumofAdultslbl.setForeground(new java.awt.Color(255, 255, 255));
        NumofAdultslbl.setText("ADULT");
        Second_Page_panel.add(NumofAdultslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        Numofchildrenlbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        Numofchildrenlbl.setForeground(new java.awt.Color(255, 255, 255));
        Numofchildrenlbl.setText("CHILDREN");
        Second_Page_panel.add(Numofchildrenlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        ChildrenSpinSecondPage.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        ChildrenSpinSecondPage.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ChildrenSpinSecondPageStateChanged(evt);
            }
        });
        Second_Page_panel.add(ChildrenSpinSecondPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 50, -1));

        InfantSpinSecondPage.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        InfantSpinSecondPage.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                InfantSpinSecondPageStateChanged(evt);
            }
        });
        Second_Page_panel.add(InfantSpinSecondPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 50, -1));

        AdultSpinSecondPage.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        AdultSpinSecondPage.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AdultSpinSecondPageStateChanged(evt);
            }
        });
        Second_Page_panel.add(AdultSpinSecondPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 50, -1));

        jLabel24.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ITINERARY");
        Second_Page_panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 130, 20));

        jLabel31.setBackground(new java.awt.Color(0, 0, 0));
        jLabel31.setOpaque(true);
        Second_Page_panel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 1000, 10));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setOpaque(true);
        Second_Page_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 660, 350));

        jLabel33.setBackground(new java.awt.Color(51, 51, 51));
        jLabel33.setOpaque(true);
        Second_Page_panel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 310, 350));

        jLabel34.setBackground(new java.awt.Color(0, 0, 0));
        jLabel34.setOpaque(true);
        Second_Page_panel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 10, 350));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setRows(5);
        jTextArea1.setText("Mandatory check-list for passengers\n\nCOVID test requirements : RT-PCR test report is NOT required to enter Karnataka.\nPre-registration or e-Pass requirements : Download and update Aarogya Setu app\nQuarantine Guidelines : None\nDestination Restrictions : A lockdown is in effect at the moment, however, flight operations remain unaffected during this time. Please check the latest state guidelines before travelling.\nRemember to web check-in before arriving at the airport; carry a printed or soft copy of the boarding pass.\nPlease reach at least 2 hours prior to flight departure.\nThe latest DGCA guidelines state that it is compulsory to wear a mask that covers the nose and mouth properly while at the airport and on the flight. Any lapse might result in de-boarding. Know More\nRemember to download the baggage tag(s) and affix it on your bag(s).\n\nState Guidelines\n\nCheck the detailed list of travel guidelines issued by Indian States and UTs.Know More\nBaggage information\n\nCarry no more than 1 check-in baggage and 1 hand baggage per passenger. Additional pieces of Baggage will be subject to additional charges per piece in addition to the excess baggage charges.\nA Note on Guidelines\n\nThe information provided above is only for ready reference and convenience of customers, and is not exhaustive. \nWe strongly recommend that you check the full text of the guidelines issued by the State Government or District Administration of the city of origin, \ntransit cities and destination city around travel restrictions or requirements before booking and/or undertaking travel.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        Second_Page_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 1010, 180));

        infantcostlbl1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        infantcostlbl1.setForeground(new java.awt.Color(255, 255, 255));
        Second_Page_panel.add(infantcostlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 70, 20));

        AgreeAndProceedBTN.setBackground(new java.awt.Color(0, 0, 0));
        AgreeAndProceedBTN.setForeground(new java.awt.Color(255, 255, 255));
        AgreeAndProceedBTN.setText("PROCEED");
        AgreeAndProceedBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgreeAndProceedBTNActionPerformed(evt);
            }
        });
        Second_Page_panel.add(AgreeAndProceedBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 620, 120, -1));

        BackBTN.setBackground(new java.awt.Color(0, 0, 0));
        BackBTN.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN.setText("BACK");
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        Second_Page_panel.add(BackBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 110, -1));

        getContentPane().add(Second_Page_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1060, 660));
        Second_Page_panel.setVisible(false);

        First_page_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fromLabel.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        fromLabel.setText("TO");
        First_page_panel.add(fromLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        fromLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        fromLabel2.setText("FROM");
        First_page_panel.add(fromLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        FromComboBox.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        FromComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--SELECT-->", "NEW DELHI", "BANGALORE", "MUMBAI", "BELAGAVI", "KOLKATA", "CHENNAI", "HYDERABAD", "AMRITSAR", "GUWAHATI", "AHMEDABAD", "MANGALORE", "KOCHI", "JAIPUR", "LUCKNOW" }));
        FromComboBox.setToolTipText("SELECT");
        FromComboBox.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        FromComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FromComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromComboBoxActionPerformed(evt);
            }
        });
        First_page_panel.add(FromComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 130, 25));

        ToComboBox.setBackground(new java.awt.Color(153, 153, 153));
        ToComboBox.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        ToComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--SELECT-->", "NEW DELHI", "BANGALORE", "MUMBAI", "BELAGAVI", "KOLKATA", "CHENNAI", "HYDERABAD", "AMRITSAR", "GUWAHATI", "AHMEDABAD", "MANGALORE", "KOCHI", "JAIPUR", "LUCKNOW" }));
        ToComboBox.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        ToComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ToComboBox.setPreferredSize(new java.awt.Dimension(92, 50));
        ToComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToComboBoxActionPerformed(evt);
            }
        });
        First_page_panel.add(ToComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 130, 25));

        BUTTONGROUP.add(OneWayTripRB);
        OneWayTripRB.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        OneWayTripRB.setSelected(true);
        OneWayTripRB.setText("ONE WAY ");
        First_page_panel.add(OneWayTripRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        BUTTONGROUP.add(RoundTripRB);
        RoundTripRB.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        RoundTripRB.setText("ROUND TRIP");
        RoundTripRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoundTripRBActionPerformed(evt);
            }
        });
        First_page_panel.add(RoundTripRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        SearchButton.setBackground(new java.awt.Color(0, 0, 0));
        SearchButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setText("SEARCH");
        SearchButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        First_page_panel.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 90, 60));

        SwapLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SwapLabelMouseClicked(evt);
            }
        });
        First_page_panel.add(SwapLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 30, 30));

        DateSelector.setFont(new java.awt.Font("Microsoft Tai Le", 0, 11)); // NOI18N
        First_page_panel.add(DateSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 160, -1));

        Arriveslbl.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        Arriveslbl.setText("RETURN");
        First_page_panel.add(Arriveslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        Departurelbl.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        Departurelbl.setText("DEPARTURE");
        First_page_panel.add(Departurelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        DateSelector1.setDateFormatString("dd/MM/yyyy");
        DateSelector1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        First_page_panel.add(DateSelector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 150, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel1.setText("TRAVELLERS : ");
        First_page_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel2.setText("INFANT");
        First_page_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel3.setText("ADULT");
        First_page_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel4.setText("CHILDREN");
        First_page_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        ChildrenSpin.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        ChildrenSpin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ChildrenSpinStateChanged(evt);
            }
        });
        First_page_panel.add(ChildrenSpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 50, -1));

        InfantSpin.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        InfantSpin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                InfantSpinStateChanged(evt);
            }
        });
        First_page_panel.add(InfantSpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 50, -1));

        AdultSpin.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        AdultSpin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AdultSpinStateChanged(evt);
            }
        });
        First_page_panel.add(AdultSpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 50, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel6.setText("CURRENCY : ");
        First_page_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIAN RUPEES", "US DOLLARS", "THAILAND BAHT", "UAE DIHRAM", "SINGAPORE DOLLAR", "BRITISH POUNDS", "BANGLADESHI TAKA", "KUWAITI DINAR", "SRI LANKAN RUPEE" }));
        First_page_panel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 485, 160, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\username\\Desktop\\clipart223987.png")); // NOI18N
        First_page_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 90, 60));

        FlightDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        FlightDisplayTable.setAutoscrolls(false);
        FlightDisplayTable.setShowGrid(false);
        FlightDisplayTableJScroll.setViewportView(FlightDisplayTable);

        First_page_panel.add(FlightDisplayTableJScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 670, 150));

        welcomeLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\username\\Downloads\\hqdefault.jpg")); // NOI18N
        welcomeLbl.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        First_page_panel.add(welcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 135, 560, 350));
        welcomeLbl.setVisible(true);

        AirIndialbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\username\\Downloads\\airindia.jpg")); // NOI18N
        AirIndialbl.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        First_page_panel.add(AirIndialbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 135, 560, 350));
        AirIndialbl.setVisible(false);

        AirAsialbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\username\\Downloads\\AirAsia.jpg")); // NOI18N
        AirAsialbl.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        First_page_panel.add(AirAsialbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 135, 560, 350));
        AirAsialbl.setVisible(false);

        Indigolbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\username\\Downloads\\IndiGo-s.jpg")); // NOI18N
        Indigolbl.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        First_page_panel.add(Indigolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 135, 560, 350));
        Indigolbl.setVisible(false);

        SpiceJetlbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\username\\Downloads\\SpiceJet1PTI12.jpg")); // NOI18N
        SpiceJetlbl.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        First_page_panel.add(SpiceJetlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 135, -1, -1));
        SpiceJetlbl.setVisible(false);

        StartAirwayslbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\username\\Downloads\\star-airways.jpg")); // NOI18N
        StartAirwayslbl.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        First_page_panel.add(StartAirwayslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 135, -1, -1));
        StartAirwayslbl.setVisible(false);

        loginButton.setContentAreaFilled(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        First_page_panel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1103, 23, 50, 40));

        NextBtn.setBackground(new java.awt.Color(0, 0, 0));
        NextBtn.setForeground(new java.awt.Color(255, 255, 255));
        NextBtn.setText("NEXT");
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });
        First_page_panel.add(NextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 660, -1, -1));

        userlbl.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        First_page_panel.add(userlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(973, 35, 110, -1));

        BACKGROUND.setIcon(new javax.swing.ImageIcon("C:\\Users\\username\\Desktop\\SEARCH_FLIGHT_1.png")); // NOI18N
        First_page_panel.add(BACKGROUND, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1150, -1));

        getContentPane().add(First_page_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -14, 1200, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FromComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromComboBoxActionPerformed

    private void ToComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ToComboBoxActionPerformed

    public void createTable(String[] columnNames)
    {
        model = new DefaultTableModel() ;

        model.setColumnIdentifiers(columnNames);




       FlightDisplayTable = new JTable(model){
       public boolean isCellEditable(int row,int column){
         Object o = getValueAt(row,column);
         return false;

       }
     };
        FlightDisplayTable.setModel(model);
        FlightDisplayTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        FlightDisplayTable.setFillsViewportHeight(true);
        FlightDisplayTable.setShowGrid(true); ;
        FlightDisplayTable.setGridColor(Color.black);
     //  FlightDisplayTable.isEditing()
       // JScrollPane scroll = new JScrollPane(FlightDisplayTable);
        FlightDisplayTableJScroll.setViewportView(FlightDisplayTable);
        FlightDisplayTableJScroll.setHorizontalScrollBarPolicy(

                JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        FlightDisplayTableJScroll.setVerticalScrollBarPolicy(

                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

    }


    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        String source = FromComboBox.getSelectedItem().toString() ;
           String destination = ToComboBox.getSelectedItem().toString() ;
           java.util.Date date = DateSelector.getDate() ;
            SimpleDateFormat formatterDate = new SimpleDateFormat("yyyy/MM/dd");
           String strDate= formatterDate.format(date);
           String strTime ;
           String[] columnNames = null ;
           int columnCount ;
          try {
              //stmt = conn.createStatement() ;
              //rs = stmt.executeQuery("SELECT * FROM PROJECT_FLIGHT") ;
             pstmt = conn.prepareStatement("SELECT * FROM PROJECT_FLIGHT WHERE SOURCE = '" + source + "' AND DESTINATION = '" + destination + "' AND DEPARTURE LIKE "
                     + "TO_DATE('"+strDate+"','YYYY/MM/DD')") ;
              System.out.println("SELECT * FROM PROJECT_FLIGHT WHERE SOURCE = '" + source + "' AND DESTINATION = '" + destination + "' AND DEPARTURE LIKE "
                     + "TO_DATE('"+strDate+"','YYYY/MM/DD')");
             rs = pstmt.executeQuery();
             metadata = pstmt.getMetaData() ;
             columnCount = metadata.getColumnCount() ;
             columnNames = new String[columnCount] ;
             for(int i = 0 ; i < columnCount ; i++)
             {
                 columnNames[i] = metadata.getColumnName(i + 1 ) ;
             }
             createTable(columnNames);


           while(rs.next())
           {
                From = rs.getString("SOURCE")  ;
             To = rs.getString("DESTINATION") ;
             Fname = rs.getString("FNAME") ;
             Fno = rs.getString("FNO") ;
             Dept = rs.getString("DEPARTURE") ;
             Date = strDate ;
             Time = Dept.substring(Dept.length()- 10, Dept.length()-2) ;
             CostPerSeat = Integer.parseInt(rs.getString("COST_PER_SEAT")) ;

               model.addRow(new Object[]{Fname ,Fno,From,To ,Dept,rs.getString("RETURN")
               ,CostPerSeat,rs.getString("SEATS_AVAILABLE"),rs.getString("BOOKED_SEATS")});
               welcomeLbl.setVisible(false);

               if(rs.getString("FNAME").equals("INDIGO"))
               {
                   Indigolbl.setVisible(true);
                   SpiceJetlbl.setVisible(false);
                   AirIndialbl.setVisible(false);
                   StartAirwayslbl.setVisible(false);
                   AirAsialbl.setVisible(false);

               }
               else if(rs.getString("FNAME").equals("SPICEJET"))
               {
                   Indigolbl.setVisible(false);
                   SpiceJetlbl.setVisible(true);
                   AirIndialbl.setVisible(false);
                   StartAirwayslbl.setVisible(false);
                   AirAsialbl.setVisible(false);
               }
               else if(rs.getString("FNAME").equals("AIR-INDIA"))
               {
                   Indigolbl.setVisible(false);
                   SpiceJetlbl.setVisible(false);
                   AirIndialbl.setVisible(true);
                   StartAirwayslbl.setVisible(false);
                   AirAsialbl.setVisible(false);
               }
               else if(rs.getString("FNAME").equals("STAR-AIRWAYS"))
               {
                   Indigolbl.setVisible(false);
                   SpiceJetlbl.setVisible(false);
                   AirIndialbl.setVisible(false);
                   StartAirwayslbl.setVisible(true);
                   AirAsialbl.setVisible(false);
               }
               else if(rs.getString("FNAME").equals("AIR-ASIA"))
               {
                   Indigolbl.setVisible(false);
                   SpiceJetlbl.setVisible(false);
                   AirIndialbl.setVisible(false);
                   StartAirwayslbl.setVisible(false);
                   AirAsialbl.setVisible(true);
               }
           }

        } catch (Exception e) {
              System.out.println(e.getLocalizedMessage());
        }


        System.out.println(date);
        System.out.println(strDate);

    }//GEN-LAST:event_SearchButtonActionPerformed

    private void RoundTripRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoundTripRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoundTripRBActionPerformed

    private void SwapLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SwapLabelMouseClicked
        // TODO add your handling code here:
        String FromTemp ;
        String ToTemp ;
        String temp ;
        FromTemp = FromComboBox.getSelectedItem().toString() ;
        ToTemp = ToComboBox.getSelectedItem().toString() ;

        temp = FromTemp ;
        FromTemp = ToTemp ;
        ToTemp = temp ;

        FromComboBox.setSelectedItem(FromTemp);
        ToComboBox.setSelectedItem(ToTemp);

    }//GEN-LAST:event_SwapLabelMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
     /*   try {
            Thread.sleep(5000);
        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_loginButtonActionPerformed

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
        // TODO add your handling code here:
        First_page_panel.setVisible(false);
        Second_Page_panel.setVisible(true);
        Second_Page_panel.setBounds(0, 0, 1060, 630);
        this.setBounds(0, 0, 1060, 700);
        this.setLocationRelativeTo(null);
        System.out.println(From);

        Fromlbl.setText(From);
        Tolbl.setText(To);
        FlightNamelbl.setText(Fname);
        FlightNOlbl.setText(Fno);
        DepartureDatelbl.setText(Date);
        timelbl.setText(Time);

        AdultSpinSecondPage.setValue(AdultSpin.getValue());
        ChildrenSpinSecondPage.setValue(ChildrenSpin.getValue());
        InfantSpinSecondPage.setValue(InfantSpin.getValue());

        xAdultlbl.setText(AdultSpin.getValue().toString());
        int tempNumOfAdult = Integer.parseInt(AdultSpin.getValue().toString());
       res1 =  CostPerSeat * tempNumOfAdult ;
       Adultcostlbl.setText(String.valueOf(res1));

       xChildrenlbl.setText(ChildrenSpin.getValue().toString());
       int tempNumOfChild = Integer.parseInt(ChildrenSpinSecondPage.getValue().toString());
       res2 =  (CostPerSeat - 2000) * tempNumOfChild ;
       childrencostlbl.setText(String.valueOf(res2));

       xInfantlbl.setText(InfantSpin.getValue().toString());
       int tempNumOfInfant = Integer.parseInt(InfantSpinSecondPage.getValue().toString());
       res3 =  (int) ((0.5 * CostPerSeat *tempNumOfInfant));
       infantcostlbl.setText(String.valueOf(res3));

       totalAmount = res1 + res2 + res3 + (Integer.parseInt(Taxeslbl.getText()));
       Totalamountlbl.setText(String.valueOf(totalAmount));









    }//GEN-LAST:event_NextBtnActionPerformed

    private void AgreeAndProceedBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgreeAndProceedBTNActionPerformed
        // TODO add your handling code here:
        int temp ;
        totalPassenger = (int) AdultSpinSecondPage.getValue() + (int) ChildrenSpinSecondPage.getValue() ;
        System.out.println(totalPassenger);
        temp = JOptionPane.showConfirmDialog(this, "Proceed to Payment ?")  ;
        if(temp==0)
        {
            /*paymentProcess.TotalPriceLabel.setText(Totalamountlbl.getText());
            paymentProcess.setVisible(true); */
        //    new LoginFrame().setVisible(true);
            SeatingArrangement sa = new SeatingArrangement() ;
            sa.SeatingArrangement(this);
            sa.setVisible(true);

        }

    }//GEN-LAST:event_AgreeAndProceedBTNActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        // TODO add your handling code here:
        Second_Page_panel.setVisible(false);
        First_page_panel.setVisible(true);
         this.setBounds(0, 0, 1150, 730);
        this.setLocationRelativeTo(null);

        AdultSpin.setValue(AdultSpinSecondPage.getValue());
        ChildrenSpin.setValue(ChildrenSpinSecondPage.getValue());
        InfantSpin.setValue(InfantSpinSecondPage.getValue());




    }//GEN-LAST:event_BackBTNActionPerformed

    private void AdultSpinSecondPageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AdultSpinSecondPageStateChanged
        // TODO add your handling code here:
       xAdultlbl.setText(AdultSpinSecondPage.getValue().toString());
       int tempNumOfAdult = Integer.parseInt(AdultSpinSecondPage.getValue().toString());
       res1 =  CostPerSeat * tempNumOfAdult ;
       Adultcostlbl.setText(String.valueOf(res1));
       totalAmount = res1 + res2 + res3 + (Integer.parseInt(Taxeslbl.getText().toString()));
       Totalamountlbl.setText(String.valueOf(totalAmount));





    }//GEN-LAST:event_AdultSpinSecondPageStateChanged

    private void ChildrenSpinSecondPageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ChildrenSpinSecondPageStateChanged
        // TODO add your handling code here:
        xChildrenlbl.setText(ChildrenSpinSecondPage.getValue().toString());

       int tempNumOfChild = Integer.parseInt(ChildrenSpinSecondPage.getValue().toString());
       res2 = (CostPerSeat - 2000) * tempNumOfChild ;
       childrencostlbl.setText(String.valueOf(res2));
       totalAmount = res1 + res2 + res3 + (Integer.parseInt(Taxeslbl.getText()));
       Totalamountlbl.setText(String.valueOf(totalAmount));


    }//GEN-LAST:event_ChildrenSpinSecondPageStateChanged

    private void InfantSpinSecondPageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_InfantSpinSecondPageStateChanged
        // TODO add your handling code here:


        xInfantlbl.setText(InfantSpinSecondPage.getValue().toString());
       int tempNumOfInfant = Integer.parseInt(InfantSpinSecondPage.getValue().toString());
       res3 =  (int) ((0.5 * CostPerSeat *tempNumOfInfant));
       infantcostlbl.setText(String.valueOf(res3));
       totalAmount = res1 + res2 + res3 + (Integer.parseInt(Taxeslbl.getText()));
       Totalamountlbl.setText(String.valueOf(totalAmount));

    }//GEN-LAST:event_InfantSpinSecondPageStateChanged

    private void AdultSpinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AdultSpinStateChanged
        // TODO add your handling code here:
        xAdultlbl.setText(AdultSpin.getValue().toString());
       int tempNumOfAdult = Integer.parseInt(AdultSpin.getValue().toString());
       res1 =  CostPerSeat * tempNumOfAdult ;
       Adultcostlbl.setText(String.valueOf(res1));
       totalAmount = res1 + res2 + res3 + (Integer.parseInt(Taxeslbl.getText()));
       Totalamountlbl.setText(String.valueOf(totalAmount));

    }//GEN-LAST:event_AdultSpinStateChanged

    private void InfantSpinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_InfantSpinStateChanged
        // TODO add your handling code here:

        xInfantlbl.setText(InfantSpin.getValue().toString());
       int tempNumOfInfant = Integer.parseInt(InfantSpinSecondPage.getValue().toString());
       res3 =  (int) ((0.5 * CostPerSeat *tempNumOfInfant));
       infantcostlbl.setText(String.valueOf(res3));
       totalAmount = res1 + res2 + res3 + (Integer.parseInt(Taxeslbl.getText()));
       Totalamountlbl.setText(String.valueOf(totalAmount));


    }//GEN-LAST:event_InfantSpinStateChanged

    private void ChildrenSpinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ChildrenSpinStateChanged
        // TODO add your handling code here:


        xChildrenlbl.setText(ChildrenSpin.getValue().toString());
       int tempNumOfChild = Integer.parseInt(ChildrenSpinSecondPage.getValue().toString());
       res2 =  CostPerSeat * tempNumOfChild ;
       childrencostlbl.setText(String.valueOf(res2));
       totalAmount = res1 + res2 + res3 + (Integer.parseInt(Taxeslbl.getText()));
       Totalamountlbl.setText(String.valueOf(totalAmount));


    }//GEN-LAST:event_ChildrenSpinStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First_page() ;
            }
        });
        try {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "username", "password") ;
            System.out.println("CONNECTION SUCCESS");
         //   stmt = conn.createStatement() ;
            
        } catch (Exception e) {
        }
        
        
    }
    public static DefaultTableModel model ;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AdultSpin;
    private javax.swing.JSpinner AdultSpinSecondPage;
    private javax.swing.JLabel Adultcostlbl;
    private javax.swing.JButton AgreeAndProceedBTN;
    private javax.swing.JLabel AirAsialbl;
    private javax.swing.JLabel AirIndialbl;
    private javax.swing.JLabel Arriveslbl;
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.ButtonGroup BUTTONGROUP;
    private javax.swing.JButton BackBTN;
    private javax.swing.JSpinner ChildrenSpin;
    private javax.swing.JSpinner ChildrenSpinSecondPage;
    private com.toedter.calendar.JDateChooser DateSelector;
    private com.toedter.calendar.JDateChooser DateSelector1;
    private javax.swing.JLabel DepartureDatelbl;
    private javax.swing.JLabel Departurelbl;
    private javax.swing.JPanel First_page_panel;
    public javax.swing.JTable FlightDisplayTable;
    private javax.swing.JScrollPane FlightDisplayTableJScroll;
    private javax.swing.JLabel FlightNOlbl;
    private javax.swing.JLabel FlightNamelbl;
    private javax.swing.JComboBox<String> FromComboBox;
    private javax.swing.JLabel Fromlbl;
    private javax.swing.JLabel Indigolbl;
    private javax.swing.JSpinner InfantSpin;
    private javax.swing.JSpinner InfantSpinSecondPage;
    private javax.swing.JButton NextBtn;
    private javax.swing.JLabel NumofAdultslbl;
    private javax.swing.JLabel Numofchildrenlbl;
    private javax.swing.JRadioButton OneWayTripRB;
    private javax.swing.JRadioButton RoundTripRB;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel Second_Page_panel;
    private javax.swing.JLabel SpiceJetlbl;
    private javax.swing.JLabel StartAirwayslbl;
    private javax.swing.JLabel SwapLabel;
    private javax.swing.JLabel Taxeslbl;
    private javax.swing.JComboBox<String> ToComboBox;
    private javax.swing.JLabel Tolbl;
    private javax.swing.JLabel Totalamountlbl;
    private javax.swing.JLabel childrencostlbl;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel fromLabel2;
    private javax.swing.JLabel infantcostlbl;
    private javax.swing.JLabel infantcostlbl1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel timelbl;
    public javax.swing.JLabel userlbl;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel xAdultlbl;
    private javax.swing.JLabel xChildrenlbl;
    private javax.swing.JLabel xInfantlbl;
    // End of variables declaration//GEN-END:variables
}
