/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservationdbms;

import static airlinereservationdbms.First_page.conn;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class LoginFrame extends javax.swing.JFrame{
    static Connection conn = null ;
    static Statement stmt = null;
    static ResultSet rs = null ;
    static ResultSetMetaData metadata = null ;
    PreparedStatement pstmt  ;
    String userID = "" ; 
    boolean temp = false ;
    First_page fp ;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();

        try {
           conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "username", "password") ;
            System.out.println("Connection success");

        } catch (Exception e) {
        }
                this.setLocationRelativeTo(null);
                this.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            System.out.println("WINDOW OPENED");
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                if(temp){
                fp.userlbl.setText(userID.toUpperCase()) ;
                System.out.println("LOGIN CLOSED");
                }else{
                fp.userlbl.setText("") ;

                }
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
                
                });

         
        
    }
    public void setFirst_pageFrame(First_page temp)
    {
        this.fp = temp ;

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UsernameTF = new javax.swing.JTextField();
        PasswordTF = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();
        forgotPasswordlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SIGNUPLBL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LOGINBACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameTF.setForeground(new java.awt.Color(147, 147, 147));
        UsernameTF.setText("USERID/MOBILE");
        UsernameTF.setToolTipText("USERID/MOBILE");
        UsernameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UsernameTF.setFocusable(false);
        UsernameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameTFFocusLost(evt);
            }
        });
        UsernameTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsernameTFMouseEntered(evt);
            }
        });
        UsernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTFActionPerformed(evt);
            }
        });
        jPanel1.add(UsernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 220, 30));

        PasswordTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PasswordTF.setFocusable(false);
        PasswordTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordTFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordTFMouseEntered(evt);
            }
        });
        jPanel1.add(PasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, 30));

        LoginBtn.setBackground(new java.awt.Color(255, 255, 255));
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\username\\Desktop\\4th_SEM_PROGRMS\\DBMS\\DBMS_PROJECT\\GUI_IMAGES_UI\\LOGIN_BUTTON.png")); // NOI18N
        LoginBtn.setContentAreaFilled(false);
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 300, 90, 40));

        forgotPasswordlbl.setForeground(new java.awt.Color(183, 183, 183));
        forgotPasswordlbl.setText("forgot password ?");
        forgotPasswordlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotPasswordlblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotPasswordlblMouseExited(evt);
            }
        });
        jPanel1.add(forgotPasswordlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(183, 183, 183));
        jLabel1.setText("New User ?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        SIGNUPLBL.setBackground(new java.awt.Color(97, 157, 236));
        SIGNUPLBL.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 12)); // NOI18N
        SIGNUPLBL.setForeground(new java.awt.Color(183, 183, 183));
        SIGNUPLBL.setText("SIGNUP");
        SIGNUPLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SIGNUPLBLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SIGNUPLBLMouseExited(evt);
            }
        });
        jPanel1.add(SIGNUPLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(57, 57, 57));
        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OR");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 403, 40, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN WITH");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 435, 70, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\username\\Desktop\\4th_SEM_PROGRMS\\DBMS\\DBMS_PROJECT\\GUI_IMAGES_UI\\icons8_google_60px.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 475, 50, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\username\\Desktop\\4th_SEM_PROGRMS\\DBMS\\DBMS_PROJECT\\GUI_IMAGES_UI\\facebook_icon.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 480, 40, 40));

        LOGINBACKGROUND.setIcon(new javax.swing.ImageIcon("C:\\Users\\username\\Desktop\\4th_SEM_PROGRMS\\DBMS\\DBMS_PROJECT\\GUI_IMAGES_UI\\LOGIN.png")); // NOI18N
        jPanel1.add(LOGINBACKGROUND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTFActionPerformed

    private void UsernameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameTFFocusGained
            if(UsernameTF.getText().equals("USERID/MOBILE"))
            {
                UsernameTF.setText("");
                UsernameTF.setForeground(new Color(0,0,0));
            }
    }//GEN-LAST:event_UsernameTFFocusGained

    private void UsernameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameTFFocusLost
        // TODO add your handling code here:
        if(UsernameTF.getText().equals(""))
            {
                UsernameTF.setText("USERID/MOBILE");
                UsernameTF.setForeground(new Color(147,147,147));
            }
    }//GEN-LAST:event_UsernameTFFocusLost

    private void PasswordTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTFMouseClicked
        // TODO add your handling code here:
                PasswordTF.setFocusable(true);

    }//GEN-LAST:event_PasswordTFMouseClicked

    private void UsernameTFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameTFMouseEntered
UsernameTF.setFocusable(true);        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTFMouseEntered

    private void PasswordTFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTFMouseEntered
        // TODO add your handling code here:
        PasswordTF.setFocusable(true);
    }//GEN-LAST:event_PasswordTFMouseEntered

    private void forgotPasswordlblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordlblMouseEntered
        // TODO add your handling code here:
        forgotPasswordlbl.setForeground(new Color(97,157,236));

    }//GEN-LAST:event_forgotPasswordlblMouseEntered

    private void forgotPasswordlblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordlblMouseExited
        // TODO add your handling code here:
        forgotPasswordlbl.setForeground(new Color(240,240,240));
    }//GEN-LAST:event_forgotPasswordlblMouseExited

    private void SIGNUPLBLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNUPLBLMouseEntered
        // TODO add your handling code here:
        SIGNUPLBL.setForeground(new Color(97,157,236));
    }//GEN-LAST:event_SIGNUPLBLMouseEntered

    private void SIGNUPLBLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNUPLBLMouseExited
        // TODO add your handling code here:
        SIGNUPLBL.setForeground(new Color(240,240,240));
    }//GEN-LAST:event_SIGNUPLBLMouseExited

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        String mobNO ;
        
        try {
        stmt = conn.createStatement() ;
        rs = stmt.executeQuery("SELECT * FROM PROJECT_USER") ;
        while(rs.next())
        {
            userID = rs.getString("USERID") ;
            mobNO = rs.getString("MOBILE_NUM") ;
            if((userID.equals(UsernameTF.getText()) && rs.getString("PASSWORD").equals(PasswordTF.getText())) || (mobNO.equals(UsernameTF.getText()) && rs.getString("PASSWORD").equals(PasswordTF.getText())) )
            {
                JOptionPane.showMessageDialog(this,"LOGIN SUCCESSFUL") ;
                temp = true ;
                this.dispose();
                
            }
           
        }    
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_LoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
          
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGINBACKGROUND;
    private static javax.swing.JButton LoginBtn;
    private javax.swing.JPasswordField PasswordTF;
    private javax.swing.JLabel SIGNUPLBL;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JLabel forgotPasswordlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
