/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservationdbms;

import javax.swing.JOptionPane;

/**
 *
 * @author nikhil2000
 */
public class PaymentProcess extends javax.swing.JFrame {

    public static int TotalPrice = 5 ;
    static String TotalPriceString ;
    /**
     * Creates new form
     */
    public PaymentProcess() {
        initComponents();
        EmptyPanel.setVisible(true);
        CreditPanel.setVisible(false);
                NetBanking.setVisible(false);
                    UPIPanel.setVisible(false);
                    
         TotalPriceString = String.valueOf(TotalPrice) ;
          TotalPriceLabel.setText(TotalPriceString) ;
          TotalPriceLabel.setVisible(true);
          
          this.setLocationRelativeTo(null);
          System.out.println(First_page.totalAmount);
        //  TotalPriceLabel.setText();
                      
    }
    public PaymentProcess(int Total)
    {
    this.TotalPrice = Total ;
 //   new PaymentProcess().setVisible(true); ;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        AllPaymentModePanelInternal = new javax.swing.JInternalFrame();
        AllPaymentModePanel = new javax.swing.JPanel();
        PaymentOptionComboBox = new javax.swing.JComboBox<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        CreditPanel = new javax.swing.JPanel();
        CardNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        ValidThruLabel = new javax.swing.JLabel();
        PAY = new javax.swing.JButton();
        NetBanking = new javax.swing.JPanel();
        HDFCRB = new javax.swing.JRadioButton();
        AXISRB = new javax.swing.JRadioButton();
        ICICIRB = new javax.swing.JRadioButton();
        KOTAKRB = new javax.swing.JRadioButton();
        SBI = new javax.swing.JRadioButton();
        CustomerLabel = new javax.swing.JLabel();
        CustomerID = new javax.swing.JTextField();
        PAY1 = new javax.swing.JButton();
        UPIPanel = new javax.swing.JPanel();
        UPITextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PAY2 = new javax.swing.JButton();
        EmptyPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TotalPriceLabel = new javax.swing.JLabel();
        MODETITLE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AllPaymentModePanelInternal.setBackground(new java.awt.Color(255, 255, 255));
        AllPaymentModePanelInternal.setVisible(true);

        AllPaymentModePanel.setBackground(new java.awt.Color(239, 239, 239));
        AllPaymentModePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PaymentOptionComboBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PaymentOptionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--Select Mode-->", "Credit / Debit / ATM Card", "Net Banking", "UPI" }));
        PaymentOptionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentOptionComboBoxActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        CreditPanel.setPreferredSize(new java.awt.Dimension(650, 287));

        CardNumber.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("CARD NUMBER ");

        ValidThruLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ValidThruLabel.setText("VALID THRU");

        PAY.setText("PAY");
        PAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreditPanelLayout = new javax.swing.GroupLayout(CreditPanel);
        CreditPanel.setLayout(CreditPanelLayout);
        CreditPanelLayout.setHorizontalGroup(
            CreditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreditPanelLayout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(CreditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ValidThruLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(CreditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
            .addGroup(CreditPanelLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(PAY, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CreditPanelLayout.setVerticalGroup(
            CreditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreditPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(CreditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87)
                .addGroup(CreditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ValidThruLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(PAY, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.add(CreditPanel, "card2");

        buttonGroup1.add(HDFCRB);
        HDFCRB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HDFCRB.setText("HDFC");

        buttonGroup1.add(AXISRB);
        AXISRB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AXISRB.setText("AXIS");

        buttonGroup1.add(ICICIRB);
        ICICIRB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ICICIRB.setText("ICICI");

        buttonGroup1.add(KOTAKRB);
        KOTAKRB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        KOTAKRB.setText("KOTAK");

        buttonGroup1.add(SBI);
        SBI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SBI.setText("SBI");

        CustomerLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CustomerLabel.setText("CUSTOMER ID");

        CustomerID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        PAY1.setText("PAY");
        PAY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAY1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NetBankingLayout = new javax.swing.GroupLayout(NetBanking);
        NetBanking.setLayout(NetBankingLayout);
        NetBankingLayout.setHorizontalGroup(
            NetBankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetBankingLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(NetBankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NetBankingLayout.createSequentialGroup()
                        .addComponent(CustomerLabel)
                        .addGap(24, 24, 24)
                        .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NetBankingLayout.createSequentialGroup()
                        .addComponent(ICICIRB)
                        .addGap(147, 147, 147)
                        .addComponent(KOTAKRB))
                    .addGroup(NetBankingLayout.createSequentialGroup()
                        .addComponent(HDFCRB)
                        .addGap(142, 142, 142)
                        .addComponent(AXISRB))
                    .addComponent(SBI))
                .addGap(67, 230, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NetBankingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PAY1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        NetBankingLayout.setVerticalGroup(
            NetBankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetBankingLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(NetBankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HDFCRB)
                    .addComponent(AXISRB))
                .addGap(18, 18, 18)
                .addGroup(NetBankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ICICIRB)
                    .addComponent(KOTAKRB))
                .addGap(31, 31, 31)
                .addComponent(SBI)
                .addGap(45, 45, 45)
                .addGroup(NetBankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(PAY1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLayeredPane1.add(NetBanking, "card3");

        UPITextfield.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Enter Mobile Number");

        PAY2.setText("PAY");
        PAY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAY2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UPIPanelLayout = new javax.swing.GroupLayout(UPIPanel);
        UPIPanel.setLayout(UPIPanelLayout);
        UPIPanelLayout.setHorizontalGroup(
            UPIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UPIPanelLayout.createSequentialGroup()
                .addGroup(UPIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UPIPanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addComponent(UPITextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UPIPanelLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(PAY2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        UPIPanelLayout.setVerticalGroup(
            UPIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UPIPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(UPIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(UPITextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(PAY2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jLayeredPane1.add(UPIPanel, "card4");

        javax.swing.GroupLayout EmptyPanelLayout = new javax.swing.GroupLayout(EmptyPanel);
        EmptyPanel.setLayout(EmptyPanelLayout);
        EmptyPanelLayout.setHorizontalGroup(
            EmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        EmptyPanelLayout.setVerticalGroup(
            EmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        jLayeredPane1.add(EmptyPanel, "card5");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("TOTAL FARE : ");

        TotalPriceLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TotalPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout AllPaymentModePanelLayout = new javax.swing.GroupLayout(AllPaymentModePanel);
        AllPaymentModePanel.setLayout(AllPaymentModePanelLayout);
        AllPaymentModePanelLayout.setHorizontalGroup(
            AllPaymentModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllPaymentModePanelLayout.createSequentialGroup()
                .addGroup(AllPaymentModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AllPaymentModePanelLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(PaymentOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AllPaymentModePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        AllPaymentModePanelLayout.setVerticalGroup(
            AllPaymentModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllPaymentModePanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(AllPaymentModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentOptionComboBox)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1)
                .addGap(26, 26, 26))
        );

        MODETITLE.setBackground(new java.awt.Color(145, 238, 220));
        MODETITLE.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        MODETITLE.setText("CHOOSE MODE OF PAYMENT");

        javax.swing.GroupLayout AllPaymentModePanelInternalLayout = new javax.swing.GroupLayout(AllPaymentModePanelInternal.getContentPane());
        AllPaymentModePanelInternal.getContentPane().setLayout(AllPaymentModePanelInternalLayout);
        AllPaymentModePanelInternalLayout.setHorizontalGroup(
            AllPaymentModePanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllPaymentModePanelInternalLayout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(AllPaymentModePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AllPaymentModePanelInternalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MODETITLE)
                .addGap(185, 185, 185))
        );
        AllPaymentModePanelInternalLayout.setVerticalGroup(
            AllPaymentModePanelInternalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllPaymentModePanelInternalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(MODETITLE)
                .addGap(18, 18, 18)
                .addComponent(AllPaymentModePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AllPaymentModePanelInternal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AllPaymentModePanelInternal)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(818, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PaymentOptionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentOptionComboBoxActionPerformed
        // TODO add your handling code here:
        
        if(PaymentOptionComboBox.getSelectedItem().equals("<--Select Mode-->"))
        {
        EmptyPanel.setVisible(true);
        CreditPanel.setVisible(false);
                NetBanking.setVisible(false);
                    UPIPanel.setVisible(false);
                
        }
        else if(PaymentOptionComboBox.getSelectedItem().equals("Credit / Debit / ATM Card"))
        {
            CreditPanel.setVisible(true);
                NetBanking.setVisible(false);
                    NetBanking.setVisible(false);
                    EmptyPanel.setVisible(false);
        }
        else if(PaymentOptionComboBox.getSelectedItem().equals("Net Banking"))
        {
               CreditPanel.setVisible(false);
                NetBanking.setVisible(true);
                    UPIPanel.setVisible(false);
                          EmptyPanel.setVisible(false);            
        }
        else if(PaymentOptionComboBox.getSelectedItem().equals("UPI")) 
        {
                   CreditPanel.setVisible(false);
                         NetBanking.setVisible(false);
                             UPIPanel.setVisible(true);
                                      EmptyPanel.setVisible(false);

        }
    }//GEN-LAST:event_PaymentOptionComboBoxActionPerformed

    private void PAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAYActionPerformed
        // TODO add your handling code here:
        //default icon, custom title
        boolean Closed = false ;
int n = JOptionPane.showConfirmDialog(
   AllPaymentModePanelInternal ,
    "Confirm Payment ? ", "",
    JOptionPane.YES_NO_OPTION);

if(n == 0)
{
    setVisible(false);
    Closed = true ;
}
else{

    Closed = false ;
}
if(Closed)
{
  //  PassengerDetails
   // LoginFrame.ClosePassengerDetails() ;
}
    }//GEN-LAST:event_PAYActionPerformed

    private void PAY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PAY1ActionPerformed

    private void PAY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAY2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PAY2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentProcess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AXISRB;
    private javax.swing.JPanel AllPaymentModePanel;
    private javax.swing.JInternalFrame AllPaymentModePanelInternal;
    private javax.swing.JTextField CardNumber;
    private javax.swing.JPanel CreditPanel;
    private javax.swing.JTextField CustomerID;
    private javax.swing.JLabel CustomerLabel;
    private javax.swing.JPanel EmptyPanel;
    private javax.swing.JRadioButton HDFCRB;
    private javax.swing.JRadioButton ICICIRB;
    private javax.swing.JRadioButton KOTAKRB;
    private javax.swing.JLabel MODETITLE;
    private javax.swing.JPanel NetBanking;
    private javax.swing.JButton PAY;
    private javax.swing.JButton PAY1;
    private javax.swing.JButton PAY2;
    private javax.swing.JComboBox<String> PaymentOptionComboBox;
    private javax.swing.JRadioButton SBI;
    public javax.swing.JLabel TotalPriceLabel;
    private javax.swing.JPanel UPIPanel;
    private javax.swing.JTextField UPITextfield;
    private javax.swing.JLabel ValidThruLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
